### ISSUE TITLE
2018 Q2 1.2: GDPR Compliance

### ISSUE THREAD

**Issue by andymckay** [mozilla/app-services-okrs#1]
Ensure that we meet legals requirements for [GDPR compliance](https://www.eugdpr.org/), which goes into effect on May 25th. This includes integrating with all our reliers (including SalesForce) to ensure appropriate levels of transparency and understanding when an account is deleted.

### Tracking bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1405204
https://bugzilla.mozilla.org/show_bug.cgi?id=1417298

### Risks
* Will require work outside this teams direct control.
* Will require some assistance from legal to review and ensure we meet their needs.

**Comment by andymckay** [comment]
mozilla/notes#788

**Comment by andymckay** [comment]
AMO Basket compliance: mozilla/addons#5346 and deleting: mozilla/addons#5393

**Comment by juliemccracken** [comment]
On track. Meeting with legal on Monday.
